# Generated by Django 4.2 on 2026-03-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_documents_and_cess'),
        ('drivers', '0002_driver_user_link'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('station_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('kerosene', 'Kerosene'), ('other', 'Other')], max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('odometer_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_tank', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('fuel_card', 'Fuel Card'), ('voucher', 'Voucher'), ('internal', 'Internal')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='drivers.driver')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fuel.fuelstation')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('distance_covered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_per_litre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('litres_per_100km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_consumptions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'unique_together': {('vehicle', 'period_start', 'period_end')},
            },
        ),
    ]
