version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: semko
      POSTGRES_USER: semko
      POSTGRES_PASSWORD: semko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
volumes:
  postgres_data:
