# Generated by Django 4.2 on 2026-03-18 12:27

import apps.users.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.user.CustomUserManager()),
            ],
        ),
    ]
