# Generated by Django 4.2 on 2026-03-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(db_index=True, help_text='The JWT token string (hashed or plaintext)')),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], default='access', help_text='Type of token: access or refresh', max_length=10)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when token was blacklisted')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when token naturally expires (for cleanup)')),
                ('reason', models.CharField(choices=[('logout', 'User Logout'), ('password_change', 'Password Changed'), ('admin_revoke', 'Admin Revocation'), ('session_timeout', 'Session Timeout')], default='logout', help_text='Reason for blacklisting', max_length=255)),
                ('user', models.ForeignKey(help_text='User who owns the blacklisted token', on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['token', 'user'], name='users_token_token_f24ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['expires_at'], name='users_token_expires_7c745a_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['user', 'token_type'], name='users_token_user_id_d06280_idx'),
        ),
    ]
