# Generated by Django 4.2 on 2026-04-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_user_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tokenblacklist',
            name='users_token_token_f24ea4_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_email_6f2530_idx',
            old_name='users_user_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_is_acti_32e7f1_idx',
            old_name='users_user_active_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_role_id_a0934c_idx',
            old_name='users_user_role_idx',
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['token_hash', 'user'], name='users_token_token_h_482b1f_idx'),
        ),
    ]
