# Generated by Django 4.2 on 2026-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_policy_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(choices=[('discrepancy', 'Discrepancy'), ('statutory', 'Statutory'), ('policy', 'Policy'), ('non_trip', 'Non Trip'), ('other', 'Other')], max_length=20),
        ),
    ]
