# Generated by Django 4.2 on 2026-03-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_driver_compensation_and_locking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusearning',
            name='bonus_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('base_salary', 'Base Salary'), ('allowance', 'Allowance'), ('non_trip', 'Non Trip'), ('other', 'Other')], max_length=20),
        ),
    ]
