# Generated by Django 4.2 on 2026-04-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_vehicles_ve_status_idx_vehicles_ve_status_3d5291_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_status_idx' AND relkind = 'i'
                        ) THEN
                            ALTER INDEX vehicles_ve_status_idx RENAME TO vehicles_ve_status_3d5291_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_status_3d5291_idx' AND relkind = 'i'
                        ) THEN
                            CREATE INDEX vehicles_ve_status_3d5291_idx ON vehicles_vehicle (status, is_active);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_status_3d5291_idx' AND relkind = 'i'
                        ) THEN
                            ALTER INDEX vehicles_ve_status_3d5291_idx RENAME TO vehicles_ve_status_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='vehicle',
                    old_name='vehicles_ve_status_idx',
                    new_name='vehicles_ve_status_3d5291_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_vehicle_idx' AND relkind = 'i'
                        ) THEN
                            ALTER INDEX vehicles_ve_vehicle_idx RENAME TO vehicles_ve_vehicle_d9d1ae_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_vehicle_d9d1ae_idx' AND relkind = 'i'
                        ) THEN
                            CREATE INDEX vehicles_ve_vehicle_d9d1ae_idx ON vehicles_vehicle (vehicle_type_id);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_vehicle_d9d1ae_idx' AND relkind = 'i'
                        ) THEN
                            ALTER INDEX vehicles_ve_vehicle_d9d1ae_idx RENAME TO vehicles_ve_vehicle_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='vehicle',
                    old_name='vehicles_ve_vehicle_idx',
                    new_name='vehicles_ve_vehicle_d9d1ae_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'vehicles_vehicle' AND column_name = 'fuel_type'
                        ) AND NOT EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_fuel_ty_34a139_idx' AND relkind = 'i'
                        ) THEN
                            CREATE INDEX vehicles_ve_fuel_ty_34a139_idx ON vehicles_vehicle (fuel_type, status);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_fuel_ty_34a139_idx' AND relkind = 'i'
                        ) THEN
                            DROP INDEX vehicles_ve_fuel_ty_34a139_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='vehicle',
                    index=models.Index(fields=['fuel_type', 'status'], name='vehicles_ve_fuel_ty_34a139_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'vehicles_vehicleownership' AND column_name = 'ownership_type'
                        ) AND NOT EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_ownersh_c32fbf_idx' AND relkind = 'i'
                        ) THEN
                            CREATE INDEX vehicles_ve_ownersh_c32fbf_idx ON vehicles_vehicleownership (ownership_type);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_ownersh_c32fbf_idx' AND relkind = 'i'
                        ) THEN
                            DROP INDEX vehicles_ve_ownersh_c32fbf_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='vehicleownership',
                    index=models.Index(fields=['ownership_type'], name='vehicles_ve_ownersh_c32fbf_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'vehicles_vehicleownership' AND column_name = 'insurance_expiry_date'
                        ) AND NOT EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_insuran_17db06_idx' AND relkind = 'i'
                        ) THEN
                            CREATE INDEX vehicles_ve_insuran_17db06_idx ON vehicles_vehicleownership (insurance_expiry_date);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM pg_class
                            WHERE relname = 'vehicles_ve_insuran_17db06_idx' AND relkind = 'i'
                        ) THEN
                            DROP INDEX vehicles_ve_insuran_17db06_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='vehicleownership',
                    index=models.Index(fields=['insurance_expiry_date'], name='vehicles_ve_insuran_17db06_idx'),
                ),
            ],
        ),
    ]
