# Generated by Django 4.2 on 2026-04-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_vehicles_ve_status_idx_vehicles_ve_status_3d5291_idx_and_more'),
    ]

    operations = [
        # This migration was generated automatically but the rename operations
        # are already covered by the previous migration in a safe way.
    ]
