export const permissions = {
  viewUsers: "users.view_user",
  manageUsers: "users.manage_user",
  viewRoles: "users.view_role",
  manageRoles: "users.manage_role",
  viewAudit: "audit.view_log",
  viewVehicles: "vehicles.view_vehicle",
  manageVehicles: "vehicles.manage_vehicle",
  viewDrivers: "drivers.view_driver",
  manageDrivers: "drivers.manage_driver",
  viewClients: "clients.view_client",
  manageClients: "clients.manage_client",
  viewTrips: "trips.view_trip",
  manageTrips: "trips.manage_trip",
  viewStores: "stores.view_store",
  manageStores: "stores.manage_store",
  viewPurchaseOrders: "stores.view_purchase_order",
  managePurchaseOrders: "stores.manage_purchase_order",
  viewFuel: "fuel.view_fuel",
  manageFuel: "fuel.manage_fuel",
  viewMaintenance: "maintenance.view_maintenance",
  manageMaintenance: "maintenance.manage_maintenance",
  viewPayroll: "payroll.view_payroll",
  managePayroll: "payroll.manage_payroll",
};
