export const appRoutes = {
  home: "/",
  login: "/login",
  unauthorized: "/unauthorized",
  app: "/app",
  dashboard: "/app/dashboard",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/app/profile",
  changePassword: "/app/password/change",
  tripDetail: (tripId: number | string) => `/app/trips/${tripId}`,
  tripCreate: "/app/trips/new",
  tripEdit: (tripId: number | string) => `/app/trips/${tripId}/edit`,
  users: "/app/users",
  userCreate: "/app/users/new",
  userDetail: (userId: number | string) => `/app/users/${userId}`,
  userEdit: (userId: number | string) => `/app/users/${userId}/edit`,
  clients: "/app/clients",
  clientCreate: "/app/clients/new",
  clientDetail: (clientId: number | string) => `/app/clients/${clientId}`,
  clientEdit: (clientId: number | string) => `/app/clients/${clientId}/edit`,
  materials: "/app/materials",
  materialCreate: "/app/materials/new",
  materialDetail: (materialId: number | string) => `/app/materials/${materialId}`,
  materialEdit: (materialId: number | string) => `/app/materials/${materialId}/edit`,
  roles: "/app/roles",
  audit: "/app/audit",
  vehicles: "/app/vehicles",
  vehicleTypes: "/app/vehicles/types",
  vehicleOwnerships: "/app/vehicles/ownerships",
  drivers: "/app/drivers",
  driverLicenses: "/app/drivers/licenses",
  driverCreate: "/app/drivers/new",
  driverDetail: (driverId: number | string) => `/app/drivers/${driverId}`,
  driverEdit: (driverId: number | string) => `/app/drivers/${driverId}/edit`,
  trips: "/app/trips",
  rules: "/app/rules",
  cess: "/app/cess",
  stores: "/app/stores",
  storesReceivings: "/app/stores/receivings",
  storesRequisitions: "/app/stores/requisitions",
  storesIssues: "/app/stores/issues",
  storesAdjustments: "/app/stores/adjustments",
  storesPurchaseOrders: "/app/stores/purchase-orders",
  storesSuppliers: "/app/stores/suppliers",
  fuel: "/app/fuel",
  fuelStations: "/app/fuel/stations",
  fuelConsumption: "/app/fuel/consumption",
  maintenance: "/app/maintenance",
  maintenanceMechanics: "/app/maintenance/mechanics",
  maintenanceServiceRecords: "/app/maintenance/service-records",
  maintenancePartsUsed: "/app/maintenance/parts-used",
  payroll: "/app/payroll",
  reports: "/app/reports",
  notifications: "/app/notifications",
  settings: "/app/settings",
  support: "/support",
  docs: "/docs",
  legal: "/legal",
};
